- backend/gradio_webrtc/webrtc.py
- demo/stream_whisper.py
- demo/video_send_output.py
- docs/advanced-configuration.md
- frontend/Index.svelte
- frontend/shared/InteractiveAudio.svelte
- frontend/shared/InteractiveVideo.svelte
- frontend/shared/Webcam.svelte
- frontend/shared/webrtc_utils.ts
- pyproject.toml
Closes #26 
Some tweaks to additional_outputs:
* Store updates in queue so that intermediate updates don't get lost
* set trigger_mode to multiple to trigger multiple updates
Some fixes to track constraints:
* Not being passed down to Webcam
* Add rtp_params to enforce via `degradationPreference`
> Additional outputs tweaks + fix track constraints

- backend/fastrtc/stream.py
- backend/fastrtc/webrtc_connection_mixin.py
- backend/fastrtc/websocket.py
- demo/talk_to_claude/app.py
- docs/index.md
- frontend/Index.svelte
- frontend/shared/InteractiveAudio.svelte
- frontend/shared/InteractiveVideo.svelte
- frontend/shared/Webcam.svelte
- frontend/shared/webrtc_utils.ts
- justfile
- pyproject.toml
The Stream no longer subclasses FastAPI, instead the library is organized around three methods:
* `stream.ui.launch()` - test with gradio, deploy as gradio if you want
* `stream.fastphone()` - get a phone to call into your stream
* `stream.mount` - add to a FastAPI app (potentially other apps in the future)
Also removing the built-in docs routes and instead going to link to a page on the docs. Should allow for faster iteration.
> Stream redesign

- demo/hello_computer/app.py
- demo/hello_computer/requirements.txt
- demo/talk_to_sambanova/app.py
- demo/talk_to_sambanova/requirements.txt
Related to https://huggingface.co/spaces/fastrtc/talk-to-sambanova-gradio/discussions/1.
This is a suggestion to use the `huggingface_hub` client instead of openai's one to call Sambanova API. No need to provide the sambanova API endpoint anymore. Also, one can use the HF model id and easily switch between providers  (currently 7 providers on https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct, user can select based on speed/cost trade-off).
More advanced suggestion would be to set a `HF_TOKEN` Space secret instead and instantiate the client like this:
```py
client = huggingface_hub.InferenceClient(
provider="sambanova",
)
```
This will provide HF routing => easier to switch between providers while keeping billing in a single place.
---
To reply to comments:
> I tested this locally …
> Use `huggingface_hub.InferenceClient` instead of `openai.OpenAI` to call Sambanova

- backend/fastrtc/webrtc_connection_mixin.py
- demo/moonshine_live/app.py
- docs/userguide/api.md
- frontend/shared/InteractiveAudio.svelte
- frontend/shared/StaticAudio.svelte
- frontend/shared/StaticVideo.svelte
- frontend/shared/Webcam.svelte
- pyproject.toml
- Properly display errors in gradio ui if concurrency limit reached
- If connection fails display a gradio error
- If after 30 seconds the backend can't connect, close the channel. Should prevent phantom connections from hogging up one of the concurrency limits
> Tidy up connection logic

- backend/fastrtc/__init__.py
- backend/fastrtc/reply_on_pause.py
- backend/fastrtc/stream.py
- backend/fastrtc/utils.py
- backend/fastrtc/webrtc.py
- backend/fastrtc/webrtc_connection_mixin.py
- demo/phonic_chat/app.py
- demo/talk_to_sambanova/app.py
- docs/userguide/streams.md
- frontend/Index.svelte
- frontend/shared/InteractiveVideo.svelte
- frontend/shared/Webcam.svelte
- pyproject.toml
Stream the outputs in a generator as opposed to sending one off requests. That helps with preventing flicker in output components as well as race conditions.
Fix a bug that was breaking video demos due to the newly added icon_radius prop not being passed in
> Video Bugfix + generator

- README.md
- docs/index.md
Added quotes around fastrtc[vad, tts] to prevent shell misinterpretation and ensure correct installation of extras.
Currently Zsh throws an error:  
```
zsh: no matches found: fastrtc[vad,stt,tts]
```
> Fix installation command by quoting package name in pip install

- backend/fastrtc/reply_on_pause.py
- backend/fastrtc/reply_on_stopwords.py
- backend/fastrtc/stream.py
- backend/fastrtc/tracks.py
- backend/fastrtc/utils.py
- backend/fastrtc/websocket.py
- demo/llm_voice_chat/app.py
- demo/moonshine_live/app.py
- demo/whisper_realtime/app.py
- demo/whisper_realtime/index.html
- docs/userguide/audio.md
- frontend/shared/InteractiveAudio.svelte
- pyproject.toml
Adds `can_interrupt` parameter that defaults to True. Modifies docs as well.
Also fixes some of the whisper demos.
> ReplyOnPause and ReplyOnStopWords can be interrupted 

- backend/fastrtc/stream.py
without additional_input_components like below 
```
stream = Stream(
handler=generation,
modality="video",
mode="receive"
)
```
cause an error
```
File "/usr/local/lib/python3.10/site-packages/fastrtc/stream.py", line 79, in __init__
self._ui = self._generate_default_ui(ui_args)
File "/usr/local/lib/python3.10/site-packages/fastrtc/stream.py", line 215, in _generate_default_ui
trigger=button.click,
UnboundLocalError: local variable 'button' referenced before assignment
```
button should be added without additional_input_components .
thanks for sharing project.
> UnboundLocalError: local variable 'button' referenced before assignment

- docs/deployment.md
Old instructions will still work, but we now have an endpoint that matches the `RTCPeerConnection` signature exactly.
> Simplify Cloudflare config with new endpoint

- backend/fastrtc/__init__.py
- backend/fastrtc/pause_detection/__init__.py
- backend/fastrtc/pause_detection/protocol.py
- backend/fastrtc/pause_detection/silero.py
- backend/fastrtc/reply_on_pause.py
- backend/fastrtc/reply_on_stopwords.py
- docs/vad_gallery.md
- mkdocs.yml
Developers can pass a `model: PauseDetectionModel` instance to reply on pause and it will be used for VAD. 
This is the required API:
```python
ModelOptions: TypeAlias = Any
class PauseDetectionModel(Protocol):
def vad(
self,
audio: tuple[int, NDArray[np.int16] | NDArray[np.float32]],
options: ModelOptions,
) -> tuple[float, list[AudioChunk]]: ...
def warmup(
self,
) -> None: ...
```
Developers can then publish their own pypi packages containing their model loading code (or whatever other method they want to use) and open a PR to the VAD gallery in the docs
> Add Method for loading community Vad Models

- backend/fastrtc/pause_detection/silero.py
Currently, if a user passes custom `SileroVadOptions`, they are never used and `vad_parameters ` is never instantiated, leading to an error.
> fix:  unused user-provided Silero option

- backend/fastrtc/reply_on_pause.py
Fixes a bug where the model parameter was not copied in ReplyOnPause.copy(), ensuring consistency in duplicated instances.
> fix: ensure 'model'  is copied in ReplyOnPause.copy()

- docs/cookbook.md
Example of an Electron app using FastRTC. Backend is a FastAPI server and basic html/js frontend.
> add fastrc with Elecron app example to cookbook

- backend/fastrtc/stream.py
Latest version of gradio introduced a new argument called `share_server_tls_certificate`
Closes #182
> Fix Fastphone bug with latest gradio version

- docs/userguide/audio.md
Since https://github.com/freddyaboulton/gradio-webrtc redirects to this repo, I assume this is an old import that was forgotten there in the example. Also, the `WebRTC` import wasn't used.
> Fix outdated import in docs

- backend/fastrtc/__init__.py
- backend/fastrtc/stream.py
- backend/fastrtc/tracks.py
- backend/fastrtc/webrtc.py
- backend/fastrtc/webrtc_connection_mixin.py
- docs/userguide/video.md
Lets Developers control the Frame Rate
Lets developers skip intermediate frames if the handler is not real time
Lets developers control when the input data is sent over in the gradio ui via send_input_on key in ui_args. Can also set directly in stream event.
Closes #152
> Some Video Fixes

- demo/gemini_audio_video/app.py
The asyncio.Event() self.quit is set twice in the __init__(), lines 52 and 55. This commit removes one of them.
> Remove twice instantiated event

- backend/fastrtc/__init__.py
- backend/fastrtc/tracks.py
- backend/fastrtc/utils.py
- backend/fastrtc/webrtc_connection_mixin.py
Added a get_contex function that returns a Context class. This class right now has one attribute, the current `webrtc_id`. This is useful for performing certain backend actions for each stream (like tracking the number of turns taken, data generated, storing conversation history).
> Add get_context function that can be used to retrieve the webrtc id

- backend/fastrtc/reply_on_pause.py
- backend/fastrtc/reply_on_stopwords.py
- backend/fastrtc/tracks.py
- demo/gemini_audio_video/app.py
- demo/gemini_conversation/app.py
- demo/talk_to_azure_openai/app.py
- demo/talk_to_gemini/app.py
- demo/talk_to_openai/app.py
- docs/advanced-configuration.md
> Ignore output_frame_size parameter

- backend/fastrtc/websocket.py
When running a FastAPI server over websockets, I was getting this message when the client disconnected:
```
ERROR   Exception in ASGI application
Traceback (most recent call last):
File "[project path]/.venv/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 243, in run_asgi
result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "[project path]/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
return await self.app(scope, receive, send)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "[project path]/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
await …
```
> Improve error handling for websockets

- backend/fastrtc/reply_on_pause.py
- backend/fastrtc/stream.py
- backend/fastrtc/webrtc_connection_mixin.py
- demo/send_text_or_audio/app.py
- demo/send_text_or_audio/index.html
Adds a `trigger_response` method to `ReplyOnPause` and `ReplyOnStopWords`. You can trigger this method via a gradio event or with a custom backend route when mounting on FastAPI. See the `demo/send_text_or_audio`
Get the current handler via `stream.webrtc_component.handlers[webrtc_id]`. You can get the current webrtc_id by passing the webrtc component as input
```python
chatbot = gr.Chatbot(type="messages", value=[])
state = gr.State(value=[])
textbox = gr.Textbox(value="", interactive=True)
stream = Stream(
ReplyOnPause(
response,  # type: ignore
input_sample_rate=16000,
),
mode="send",
modality="audio",
additional_inputs=[
chatbot,
state,
textbox,
],
additional_outputs=[chatbot, state],
additional_outputs_handler=lambda *a: (a[2], a[3]),
concurrency_limit=20 if get_space() else 5, …
```
> Add ability to trigger ReplyOnPause without waiting for pause

- backend/fastrtc/webrtc_connection_mixin.py
Closes #252 
The issue is that we wait for 10 seconds for the next additional output. So if the concurrency_limit is 1 (default), the next connection will wait ~10 seconds for the previous one to finish and display the `queue 1/1` message.
https://github.com/user-attachments/assets/e4d23a7e-0186-4021-aac7-1d4c2bc2733f
> Fix bug where additional outputs where not fetched immediately on subsequent connections

- backend/fastrtc/reply_on_pause.py
- docs/userguide/api.md
Hi @freddyaboulton , I need this log event, I want to stop a video player (in the frontend) when the user speaks for example, so this event makes it easy for me to handle that, instead of thresholding the mic video. You can see in the OpenAI realtime API that they have these two events https://platform.openai.com/docs/guides/realtime-vad
input_audio_buffer.speech_started: The start of a speech turn (We don't have this)
input_audio_buffer.speech_stopped: The end of a speech turn (same as pause_detected in FastRTC)
> Add started_talking log message in ReplyOnPause and in api.md

- backend/fastrtc/stream.py
- backend/fastrtc/webrtc.py
- backend/fastrtc/webrtc_connection_mixin.py
- demo/talk_to_sambanova/app.py
- docs/deployment.md
- docs/reference/stream.md
- pyproject.toml
Adds a server_rtc_configuration parameter to be able to set ICEcandidates in the server.
@whitphx would appreciate if you could review! 
You can test the change here: https://huggingface.co/spaces/fastrtc/talk-to-sambanova-gradio or https://huggingface.co/spaces/fastrtc/talk-to-sambanova
> Set ice candidates server

- backend/fastrtc/websocket.py
- demo/webrtc_vs_websocket/app.py
- demo/webrtc_vs_websocket/index.html
- docs/userguide/api.md
Closes #284
The issue was that we always resampled the audio to 8khz which would mean that any other sample rate would probably cause an issue. We should only sample to-from 8khz when connecting over the phone. For all other use cases, the input sample rate sent by the client should match `input_sample_rate` set in the handler. The server will return audio with a sample rate matching the `output_sample_rate` of the handler.
How to test:
- Run the server script and client scripts separately
- Note how the client will resample the audio to 24k hz sample rate before sending to the server. The server will also send audio back in 24k hz. That's why we write the audio file with 24k hz in `receive_audio_stream`
Server
```python
from fastrtc import AsyncStreamHandler, wait_for_item, Stream
import …
```
> Fix Websocket Client Processing

- backend/fastrtc/reply_on_pause.py
Related to #316 
Adds `max_continuous_speech_s` to AlgoOptions (ReplyOnPause), which gives the option to set a hard limit for how long a chunk of continuous speech can be, regardless of whether a pause is detected by the VAD model or not.
> chunk speech after s if no pause detected by VAD
