backend/gradio_webrtc/speech_to_text/stt_.py, backend/gradio_webrtc/webrtc.py, docs/advanced-configuration.md, frontend/Index.svelte, frontend/shared/AudioWave.svelte, frontend/shared/InteractiveAudio.svelte, frontend/shared/StaticAudio.svelte, frontend/shared/webrtc_utils.ts
=> Customizable icon also fix a bug where you could not import the lib without silero

backend/gradio_webrtc/webrtc.py, docs/advanced-configuration.md, docs/cookbook.md, docs/user-guide.md, frontend/Index.svelte, frontend/shared/InteractiveAudio.svelte, frontend/shared/InteractiveVideo.svelte, frontend/shared/Webcam.svelte, pyproject.toml
=> Change recording label

demo/video_send_output.py, frontend/shared/Webcam.svelte, pyproject.toml
Closes #51 
https://github.com/user-attachments/assets/c9bd6eb1-0828-47ef-b146-62472410242e
=> Send Input Data for Webcam When First Connecting

demo/video_send_output.py, docs/user-guide.md
=> Fix AsyncStreamHandler User Guide Code

.gitignore, pyproject.toml
=> Fix python 3.13

docs/deployment.md
Cloudflare offers a managed TURN service with Cloudflare Calls: https://developers.cloudflare.com/calls/
This adds instructions for generating credentials via the Cloudflare API to plug into a `Stream`'s `rtc_configuration`.
I've tested these instructions with the echo example (and `stream.ui.launch(share=True)`).
Further documentation on generating credentials is here:
https://developers.cloudflare.com/calls/turn/generate-credentials/#create-credentials
Unfortunately we don't have a Python API for this, so I've just added instructions for a raw http call with `requests`.
(yes, the output from the API is a little funky in that it has an `iceServers` property... but it's a single object, not an array! So we have to wrap it again before passing to `Stream`, sigh)
=> Add instructions for deploying with Cloudflare

demo/talk_to_smolagents/app.py, demo/voice_text_editor/app.py, demo/voice_text_editor_local/app.py
Added a Modified script to use Ollama and run locally
=> Added Script to use Ollama and run locally 

backend/fastrtc/stream.py, demo/gemini_conversation/README.md, demo/gemini_conversation/app.py
=> Use backup url

backend/fastrtc/tracks.py, docs/userguide/audio.md, pyproject.toml
start_up must be async. Adding some error handling over that.
=> Fix async echo example

backend/fastrtc/text_to_speech/test_tts.py, backend/fastrtc/text_to_speech/tts.py
Fix for this bug: https://github.com/thewh1teagle/kokoro-onnx/issues/115
=> Fix kokoro batch issue

docs/userguide/audio.md
I have made changes to the Audio Streaming `User Guide`. Please have a looking, shall I add a demo under the demo directory? 
I see that the readme is in the format of HF Model card? Should I repeat the same 
this commit fixes #122
=> feat: Added documentation for twilio integration

backend/fastrtc/__init__.py, backend/fastrtc/stream.py
Let developers add subtitles to the Stream class easily
=> Add subtitle to UIArgs

backend/fastrtc/stream.py, frontend/shared/StaticAudio.svelte, frontend/shared/StaticVideo.svelte
=> Some video send-receive bug fixes

backend/fastrtc/tracks.py, backend/fastrtc/utils.py
The WebRTC exception was not being properly raised in the "receive" case
Closes #142
=> Raise WebRTC Errors in "Receive" case

frontend/.prettierrc, frontend/Example.svelte, frontend/Index.svelte, frontend/package-lock.json, frontend/package.json, frontend/shared/InteractiveAudio.svelte, frontend/shared/InteractiveVideo.svelte, frontend/shared/MicrophoneMuted.svelte, frontend/shared/StaticAudio.svelte, frontend/shared/StaticVideo.svelte, frontend/shared/Webcam.svelte, frontend/shared/WebcamPermissions.svelte, frontend/shared/webrtc_utils.ts, justfile
New button will appear when mode="audio" and mality = "send" | "send-receive"
Closes #131
=> Add microphone mute

docs/cookbook.md
1. Added Realtime transcription with on-device Whisper example and added "local" tag
2. Fixed wrong Kyutai tag
3. Capitalized tag display names
@freddyaboulton about 3, it's just an aesthetic change - let me know if you want me to revert :)
=> Add on-device whisper example to cookbook

backend/fastrtc/utils.py, demo/talk_to_azure_openai/app.py, docs/userguide/audio.md
The sample code for the startup function will finally work 😅
=> Fix issue when the audio stream mixes sample rates and numpy array data types

backend/fastrtc/stream.py
=> Add path argument to Stream.mount to let developers mount multiple streams in the same app easily

docs/turn_taking_gallery.md
=> Added HumAwareVAD to VAD Gallery

backend/fastrtc/stream.py, backend/fastrtc/webrtc.py, backend/fastrtc/webrtc_connection_mixin.py
=> Fix gradio concurrency issue in fetching additional outputs

backend/fastrtc/text_to_speech/tts.py, docs/text_to_speech_gallery.md, mkdocs.yml
Also adds orpheus cpp to the text-to-speech gallery
=> Add text-to-speech-gallery + reword galleries to be "Plugin Ecosystem"

docs/speech_to_text_gallery.md
This pull request includes a change to the `docs/speech_to_text_gallery.md` file, adding a new entry for the Kroko-ASR model. The entry includes a description, installation instructions, and a repository link.
Additions to the documentation:
* Added a new entry for the Kroko-ASR model, including a description, installation instructions, and a repository link.
Hopefully this is what you had in mind! PR for #168
=> Add Kroko-ASR model to STT gallery

backend/fastrtc/__init__.py, backend/fastrtc/templates/component/index.js, backend/fastrtc/tracks.py, backend/fastrtc/utils.py, frontend/Index.svelte, frontend/shared/InteractiveAudio.svelte, frontend/shared/StaticAudio.svelte, frontend/shared/StaticVideo.svelte, frontend/shared/Webcam.svelte, frontend/shared/webrtc_utils.ts
Add a `CloseStream` class that can be yielded/returned from any stream handler. Upon receiving this token, the stream will be closed. 
The `CloseStream` class accepts a message parameter that can be displayed. By default it's `Stream Closed`.
=> Close Stream from Backend

pyproject.toml
* Add text-to-speech-gallery + reword galleries to be "Plugin Ecosystem" by @freddyaboulton in https://github.com/freddyaboulton/fastrtc/pull/218
* Remove twice instantiated event by @marcusvaltonen in https://github.com/freddyaboulton/fastrtc/pull/221
* Add Kroko-ASR model to STT gallery by @sgarg26 in https://github.com/freddyaboulton/fastrtc/pull/219
* Close Stream from Backend by @freddyaboulton in https://github.com/freddyaboulton/fastrtc/pull/222 Closes #129 Closes #214
* Add get_context function that can be used to retrieve the webrtc id by @freddyaboulton in https://github.com/freddyaboulton/fastrtc/pull/223 Closes #213
* @marcusvaltonen made their first contribution in https://github.com/freddyaboulton/fastrtc/pull/221
* @sgarg26 made their first contribution in …
=> Trigger 0.0.19 release

backend/fastrtc/stream.py
=> Add track_constraints to Stream class

pyproject.toml
Fix license in pyproject.toml.
Closes #244
=> MIT license

.github/workflows/tests-frontend.yml, .github/workflows/tests.yml, demo/gemini_conversation/app.py, demo/talk_to_smolagents/app.py, pyproject.toml
=> Introduce automatic linting with Github workflows

.github/workflows/tests.yml, backend/fastrtc/stream.py, backend/fastrtc/text_to_speech/tts.py, backend/fastrtc/tracks.py, backend/fastrtc/utils.py, pyproject.toml
Partially solves #247 by introducing pyright as proposed by @vvolhejn.
=> Introduce static type checking with pyright

backend/fastrtc/webrtc_connection_mixin.py, pyproject.toml
Updates for new repo name. @freddyaboulton consider changing the email as well.
=> Update old links in pyproject.toml

backend/fastrtc/templates/component/index.js, backend/fastrtc/websocket.py
get_current_context will now return the Context when called within a websocket connection
=> Be able to get current context from a websocket connection

demo/talk_to_openai/app.py, demo/talk_to_openai/index.html
- Add User transcription
- Fix chatbot UI styling
=> OpenAI Demo Minor Fixes

backend/fastrtc/templates/component/index.js, docs/userguide/video.md, frontend/Index.svelte
=> Fix WebRTC Error display in UI + Demo Code

backend/fastrtc/stream.py, backend/fastrtc/templates/component/index.js
=> Surpress Startup Logs

demo/gemini_audio_video/app.py
Only get the turn credentials if on a space
=> Fix gemini demo

backend/fastrtc/stream.py, test/test_stream.py
=> feature: Allow to pass openapi tags to mounted endpoints
